/**
 * Channel pre-flight (FASE 1) — pure checks over the same inputs the
 * composition health panel already has: the semantic document, its
 * composition and the product metadata. No EPUB is regenerated on the
 * client; every check inspects the AST + ComposeResult.
 *
 * Channels: Amazon KDP, IngramSpark and Kobo. Each check carries a
 * severity (`error` blocks the export gate, `warning`/`info` only advise —
 * principle R6: flag the doubtful, never false-positive a clean book).
 *
 * Deliberately out of scope (not client-verifiable, documented so nobody
 * "fixes" the omission):
 * - IngramSpark trim/bleed (sangrado) and 300 dpi image resolution: both
 *   require print geometry / real pixel dimensions the client cannot see.
 * - KDP image resolution is only a conservative heuristic: it fires solely
 *   when `estimatedLines` is explicitly set to a very small value.
 * - TOC NAV presence: always generated by the composer/writer, so there is
 *   nothing to check.
 */

import type { ComposeResult } from '@/lib/compose/compose';
import type { DocumentMetadata, ImageBlock, SemanticDocument } from '@/lib/document/model';

export type PreflightChannel = 'kdp' | 'ingramspark' | 'kobo';
export type PreflightSeverity = 'error' | 'warning' | 'info';

export const PREFLIGHT_CHANNELS: PreflightChannel[] = ['kdp', 'ingramspark', 'kobo'];

export interface PreflightCheck {
  channel: PreflightChannel;
  severity: PreflightSeverity;
  /** Stable rule key; the UI resolves the localized message template from it. */
  rule: string;
  /** Placeholder values for the localized message template. */
  params: Record<string, string>;
  /** 0-based page index (same convention as ComposeViolation.page), when the check anchors to a block. */
  page?: number;
  blockId?: string;
}

export interface PreflightInput {
  document: SemanticDocument;
  composed: ComposeResult;
  /** Defaults to `document.metadata`. */
  metadata?: DocumentMetadata;
  /**
   * Declared content font family (compose template), if any. KDP PKG-026:
   * the EPUB writer embeds Liberation TTFs; a declared family outside the
   * ebook-safe set is flagged because it would fall back to system fonts.
   */
  fontFamily?: string;
}

/**
 * Families considered safe for ebook channels without embedding. Generic
 * CSS families and the Liberation set the EPUB writer packages always pass;
 * common system fonts are included so a declared standard font is never a
 * false positive (conservative by design).
 */
const EBOOK_SAFE_FONTS = new Set([
  'serif',
  'sans-serif',
  'monospace',
  'cursive',
  'fantasy',
  'system-ui',
  'liberation sans',
  'liberation serif',
  'liberation mono',
  'arial',
  'helvetica',
  'georgia',
  'times new roman',
  'courier new',
  'verdana',
  'tahoma',
  'trebuchet ms',
]);

/**
 * KDP resolution heuristic: only fires when the composer estimate says the
 * image renders below this many base lines (a divider-sized image whose
 * source is likely too small). Real dpi is not client-verifiable.
 */
const KDP_SMALL_IMAGE_LINES = 4;

/** Truncates a potentially huge src (data URIs) for message params. */
function shortSrc(src: string): string {
  return src.length > 48 ? `${src.slice(0, 45)}…` : src;
}

/** First composed page index (ComposeViolation convention) for a block. */
function pageOfBlock(composed: ComposeResult, blockId: string): number | undefined {
  for (const page of composed.pages) {
    if (page.placements.some((placement) => placement.blockId === blockId)) {
      return page.index;
    }
  }
  return undefined;
}

function imageBlocks(document: SemanticDocument): ImageBlock[] {
  return document.blocks.filter((block): block is ImageBlock => block.type === 'image');
}

function anchorCheck(
  check: Omit<PreflightCheck, 'page'>,
  composed: ComposeResult,
): PreflightCheck {
  if (!check.blockId) return check;
  const page = pageOfBlock(composed, check.blockId);
  return page !== undefined ? { ...check, page } : check;
}

/** Amazon KDP (PKG-026 fonts, images, metadata, language tagging). */
export function preflightKdp(input: PreflightInput): PreflightCheck[] {
  const { document, composed, fontFamily } = input;
  const metadata = input.metadata ?? document.metadata;
  const checks: PreflightCheck[] = [];

  if (!metadata.title?.trim()) {
    checks.push({ channel: 'kdp', severity: 'error', rule: 'kdp.metadata.title', params: {} });
  }
  if (!metadata.author?.trim()) {
    checks.push({ channel: 'kdp', severity: 'error', rule: 'kdp.metadata.author', params: {} });
  }
  if (!metadata.isbn?.trim()) {
    checks.push({ channel: 'kdp', severity: 'info', rule: 'kdp.metadata.isbn', params: {} });
  }
  if (!metadata.language?.trim()) {
    checks.push({ channel: 'kdp', severity: 'warning', rule: 'kdp.metadata.language', params: {} });
  }

  for (const image of imageBlocks(document)) {
    if (!image.alt?.trim()) {
      checks.push(
        anchorCheck(
          {
            channel: 'kdp',
            severity: 'warning',
            rule: 'kdp.image.alt',
            params: { src: shortSrc(image.src) },
            blockId: image.id,
          },
          composed,
        ),
      );
    }
    if (image.estimatedLines !== undefined && image.estimatedLines < KDP_SMALL_IMAGE_LINES) {
      checks.push(
        anchorCheck(
          {
            channel: 'kdp',
            severity: 'info',
            rule: 'kdp.image.resolution',
            params: { lines: String(image.estimatedLines) },
            blockId: image.id,
          },
          composed,
        ),
      );
    }
  }

  if (fontFamily && !EBOOK_SAFE_FONTS.has(fontFamily.trim().toLowerCase())) {
    checks.push({
      channel: 'kdp',
      severity: 'warning',
      rule: 'kdp.fonts.embed',
      params: { font: fontFamily },
    });
  }

  return checks;
}

/**
 * IngramSpark. Trim/bleed and 300 dpi are NOT checked here: both require
 * print geometry / pixel data unavailable on the client (see module doc).
 */
export function preflightIngramSpark(input: PreflightInput): PreflightCheck[] {
  const { document, composed } = input;
  const metadata = input.metadata ?? document.metadata;
  const checks: PreflightCheck[] = [];

  if (!metadata.isbn?.trim()) {
    checks.push({
      channel: 'ingramspark',
      severity: 'error',
      rule: 'ingram.metadata.isbn',
      params: {},
    });
  }
  if (!metadata.description?.trim()) {
    checks.push({
      channel: 'ingramspark',
      severity: 'info',
      rule: 'ingram.metadata.description',
      params: {},
    });
  }

  for (const image of imageBlocks(document)) {
    // Legacy data URIs and external http(s) URLs put packaging at risk: the
    // image must be an uploaded asset (blob:/relative path) so the EPUB
    // writer can embed it deterministically.
    const origin = image.src.startsWith('data:')
      ? 'data-uri'
      : /^https?:\/\//i.test(image.src)
        ? 'external-url'
        : null;
    if (origin) {
      checks.push(
        anchorCheck(
          {
            channel: 'ingramspark',
            severity: 'warning',
            rule: 'ingram.image.packaging',
            params: { src: shortSrc(image.src), origin },
            blockId: image.id,
          },
          composed,
        ),
      );
    }
  }

  return checks;
}

/** Kobo (metadata + EPUB accessibility). */
export function preflightKobo(input: PreflightInput): PreflightCheck[] {
  const { document, composed } = input;
  const metadata = input.metadata ?? document.metadata;
  const checks: PreflightCheck[] = [];

  if (!metadata.title?.trim()) {
    checks.push({ channel: 'kobo', severity: 'error', rule: 'kobo.metadata.title', params: {} });
  }
  if (!metadata.author?.trim()) {
    checks.push({ channel: 'kobo', severity: 'error', rule: 'kobo.metadata.author', params: {} });
  }
  if (!metadata.language?.trim()) {
    checks.push({ channel: 'kobo', severity: 'error', rule: 'kobo.metadata.language', params: {} });
  }

  for (const image of imageBlocks(document)) {
    if (!image.alt?.trim()) {
      checks.push(
        anchorCheck(
          {
            channel: 'kobo',
            severity: 'warning',
            rule: 'kobo.a11y.imageAlt',
            params: { src: shortSrc(image.src) },
            blockId: image.id,
          },
          composed,
        ),
      );
    }
  }

  // Heading hierarchy: jumping more than one level (H1 → H3) breaks the
  // accessible navigation of the EPUB. The first heading never counts.
  let previousLevel: number | null = null;
  for (const block of document.blocks) {
    if (block.type !== 'heading') continue;
    if (previousLevel !== null && block.level - previousLevel > 1) {
      checks.push(
        anchorCheck(
          {
            channel: 'kobo',
            severity: 'warning',
            rule: 'kobo.a11y.headingJump',
            params: { from: String(previousLevel), to: String(block.level) },
            blockId: block.id,
          },
          composed,
        ),
      );
    }
    previousLevel = block.level;
  }

  return checks;
}

const CHECKS_BY_CHANNEL: Record<PreflightChannel, (input: PreflightInput) => PreflightCheck[]> = {
  kdp: preflightKdp,
  ingramspark: preflightIngramSpark,
  kobo: preflightKobo,
};

/** Runs the pre-flight for the given channels (default: all three). */
export function preflight(
  input: PreflightInput,
  channels: PreflightChannel[] = PREFLIGHT_CHANNELS,
): PreflightCheck[] {
  return channels.flatMap((channel) => CHECKS_BY_CHANNEL[channel](input));
}

/** Errors are the only severity that blocks the export gate (R6). */
export function countPreflightErrors(checks: PreflightCheck[]): number {
  return checks.filter((check) => check.severity === 'error').length;
}
