'use client';

/**
 * Step 8 — Exportar. The final publishing gate: choose a format, see exactly what will be produced, check the book,
 * generate the artifact and verify it. It orchestrates the existing export routes (nothing is built here), takes
 * availability from `getProjectCapabilities`, and never reports success on "HTTP 200" alone: the generated bytes are
 * verified (`validateExportArtifact`) before the file is offered.
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import {
  AlertTriangle,
  BookOpen,
  CheckCircle2,
  ChevronRight,
  CircleDot,
  Code2,
  Download,
  FileText,
  Globe,
  Loader2,
  MinusCircle,
  ShieldAlert,
  XCircle,
} from 'lucide-react';
import type { AppMessages } from '@/lib/i18n/messages';
import type { ComposeViolation } from '@/lib/compose/compose';
import type { PreflightCheck } from '@/lib/preflight/preflight';
import type { KdpDisclosure } from '@/lib/ai/kdp-disclosure';
import type { ProjectRecord } from '@/lib/projects/types';
import type { ProjectCapabilities } from '@/lib/projects/capabilities';
import type { DocumentRules } from '@/lib/compose/rules';
import { getBackCoverDesign, getCoverDesign } from '@/lib/projects/design-surface-repository';
import { isEmptyDesignSurface } from '@/lib/projects/design-surface';
import { buildPreflightRows } from '@/lib/preview/preview-workspace';
import { validateExportArtifact, type ArtifactValidation } from '@/lib/projects/export-artifact';
import {
  EXPORT_FORMATS,
  PAGE_SIZE_OPTIONS,
  buildExportUrl,
  effectivePageSize,
  exportFileName,
  formatAvailability,
  formatDefinition,
  formatFileSize,
  formatGate,
  isOriginalPdfExport,
  pageSizeLabel,
  summarizeExportGeometry,
  type ExportFormat,
} from '@/lib/projects/export-workspace';
import { CreateEditableCopyButton } from '../CreateEditableCopyButton';
import { KdpDisclosurePanel } from '../KdpDisclosurePanel';

type Copy = AppMessages['project'];

export interface ExportWorkspaceProps {
  project: ProjectRecord;
  copy: Copy;
  locale: string;
  capabilities: ProjectCapabilities;
  /** Query the export routes already understand (composition/preferences), e.g. `device=laptop&marginTop=…`. */
  exportQuery: string;
  exportGate: DocumentRules['exportGate'];
  violations: ComposeViolation[];
  checks: PreflightCheck[];
  kdpDisclosure?: KdpDisclosure;
  onNavigateStep: (step: number) => void;
  onOpenDocumentData: () => void;
  /** Launch pack / sales channels panels kept from the previous step (collapsible). */
  children?: React.ReactNode;
}

interface GeneratedFile {
  id: string;
  format: ExportFormat;
  fileName: string;
  size: number;
  createdAt: string;
  url: string;
  validation: ArtifactValidation;
}

type RunState =
  | { status: 'idle' }
  | { status: 'busy'; format: ExportFormat }
  | { status: 'error'; format: ExportFormat; message: string; failedChecks?: string[] }
  | { status: 'done'; file: GeneratedFile };

const FORMAT_ICONS = { pdf: FileText, epub: BookOpen, docx: FileText, html: Globe, markdown: Code2 } as const;

function formatLabel(format: ExportFormat) {
  return { pdf: 'PDF', epub: 'EPUB', docx: 'DOCX', html: 'HTML', markdown: 'Markdown' }[format];
}

function formatDescription(copy: Copy, format: ExportFormat, original: boolean) {
  return {
    pdf: original ? copy.exWsPdfOriginalDesc : copy.exWsPdfDesc,
    epub: copy.exWsEpubDesc,
    docx: copy.exWsDocxDesc,
    html: copy.exWsHtmlDesc,
    markdown: copy.exWsMarkdownDesc,
  }[format];
}

function kindLabel(copy: Copy, kind: ReturnType<typeof formatDefinition>['kind']) {
  return { 'fixed-layout': copy.exWsKindFixed, reflowable: copy.exWsKindReflow, editable: copy.exWsKindEditable, web: copy.exWsKindWeb, text: copy.exWsKindText }[kind];
}

function validationLabel(copy: Copy, id: string): string {
  const key = `exWsV${id.charAt(0).toUpperCase()}${id.slice(1)}` as keyof Copy;
  return String(copy[key] ?? id);
}

function countWords(project: ProjectRecord): number {
  let words = 0;
  for (const chapter of project.document.chapters) {
    for (const block of chapter.blocks) {
      const text = block.content.replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').trim();
      if (text) words += text.split(/\s+/).length;
    }
  }
  return words;
}

function fileNameFromHeader(header: string | null): string | null {
  return header?.match(/filename="?([^";]+)"?/i)?.[1] ?? null;
}

export function ExportWorkspace(props: ExportWorkspaceProps) {
  const { project, copy, locale, capabilities, exportQuery, exportGate, violations, checks } = props;
  const originalPdf = isOriginalPdfExport('pdf', capabilities);
  const [format, setFormat] = useState<ExportFormat>('pdf');
  const [pageSize, setPageSize] = useState(() => effectivePageSize(exportQuery));
  const [run, setRun] = useState<RunState>({ status: 'idle' });
  const [files, setFiles] = useState<GeneratedFile[]>([]);
  const [launchOpen, setLaunchOpen] = useState(false);
  const urlsRef = useRef<string[]>([]);
  const busy = run.status === 'busy';

  useEffect(() => () => urlsRef.current.forEach((url) => URL.revokeObjectURL(url)), []);

  const definition = formatDefinition(format);
  const availability = formatAvailability(format, capabilities);
  const gate = useMemo(
    () => formatGate({ format, exportGate, violations, checks, capabilities }),
    [capabilities, checks, exportGate, format, violations],
  );
  const geometry = useMemo(() => summarizeExportGeometry(exportQuery, pageSize), [exportQuery, pageSize]);
  const words = useMemo(() => countWords(project), [project]);
  const slug = project.slug || undefined;
  const fileName = exportFileName(slug, format, copy.previewExportFilename);
  const original = format === 'pdf' && originalPdf;
  const exportBlocked = !availability.available || gate.blocked;
  const sourcePagination = project.document.metadata?.sourcePageMap?.status === 'VALID';

  const coverDesigned = useMemo(() => !isEmptyDesignSurface(getCoverDesign(project)), [project]);
  const backCoverDesigned = useMemo(() => !isEmptyDesignSurface(getBackCoverDesign(project)), [project]);
  const rows = useMemo(
    () => buildPreflightRows({ checks, violations, toLogicalPage: (page) => page }),
    [checks, violations],
  );

  const metadata = project.document.metadata as ({ isbn?: string } & Record<string, unknown>) | undefined;
  const isbn = metadata?.isbn;
  const pageNumbering = project.document.metadata?.referenceEditorialProfile?.pageNumber?.enabled ?? true;

  const renderCheck = (check: PreflightCheck) => {
    const template = copy.preflightRules[check.rule];
    if (!template) return check.rule;
    return Object.entries(check.params).reduce((message, [key, value]) => message.replaceAll(`{${key}}`, value), template);
  };

  const aiState = props.kdpDisclosure
    ? props.kdpDisclosure.status === 'required' ? { text: copy.exWsAiRequired, tone: 'info' as const }
      : props.kdpDisclosure.status === 'exempt-unconfirmed' ? { text: copy.exWsAiUnconfirmed, tone: 'unchecked' as const }
        : { text: copy.exWsAiNotRequired, tone: 'ok' as const }
    : null;

  type Row = { id: string; label: string; detail: string; tone: 'ok' | 'warning' | 'error' | 'info' | 'unchecked'; note?: string; target: () => void };
  const rowFor = (id: 'fonts' | 'images' | 'metadata' | 'composition', label: string, target: () => void): Row => {
    const source = rows.find((row) => row.id === id)!;
    return {
      id,
      label,
      detail: source.findings.length === 0 ? copy.exWsCheckOk : copy.exWsCheckIssues.replace('{count}', String(source.findings.length)),
      tone: source.status === 'unchecked' ? 'unchecked' : source.status,
      note: source.partial && source.findings.length === 0 ? copy.exWsCheckPartial : undefined,
      target,
    };
  };
  const checkRows: Row[] = [
    { id: 'content', label: copy.exWsCheckContent, detail: copy.exWsCheckContentDetail.replace('{chapters}', String(project.document.chapters.length)).replace('{words}', String(words)), tone: words > 0 ? 'ok' : 'warning', target: () => props.onNavigateStep(2) },
    ...(originalPdf ? [] : [
      { id: 'cover', label: copy.exWsCheckCover, detail: coverDesigned ? copy.exWsCheckCoverOk : copy.exWsCheckCoverEmpty, tone: coverDesigned ? 'ok' as const : 'warning' as const, target: () => props.onNavigateStep(3) },
      { id: 'back-cover', label: copy.exWsCheckBackCover, detail: backCoverDesigned ? copy.exWsCheckCoverOk : copy.exWsCheckCoverEmpty, tone: backCoverDesigned ? 'ok' as const : 'warning' as const, target: () => props.onNavigateStep(4) },
      rowFor('metadata', copy.exWsCheckMetadata, props.onOpenDocumentData),
      rowFor('fonts', copy.exWsCheckFonts, () => props.onNavigateStep(1)),
      rowFor('images', copy.exWsCheckImages, () => props.onNavigateStep(2)),
      rowFor('composition', copy.exWsCheckComposition, () => props.onNavigateStep(1)),
    ]),
    ...(aiState ? [{ id: 'ai', label: copy.exWsCheckAi, detail: aiState.text, tone: aiState.tone, target: () => props.onNavigateStep(7) }] : []),
  ];

  const generate = async () => {
    if (busy || exportBlocked) return;
    setRun({ status: 'busy', format });
    try {
      const response = await fetch(buildExportUrl(format, project.id, exportQuery, { pageSize, original }));
      if (!response.ok) {
        let detail = '';
        try { detail = ((await response.json()) as { error?: string }).error ?? ''; } catch { /* non-JSON body */ }
        setRun({ status: 'error', format, message: detail || copy.exWsErrorHttp.replace('{status}', String(response.status)) });
        return;
      }
      const bytes = new Uint8Array(await response.arrayBuffer());
      const validation = await validateExportArtifact(format, bytes, response.headers.get('content-type') ?? '');
      if (!validation.ok) {
        setRun({ status: 'error', format, message: copy.exWsResultFailed, failedChecks: validation.checks.filter((check) => !check.ok).map((check) => validationLabel(copy, check.id)) });
        return;
      }
      const name = fileNameFromHeader(response.headers.get('content-disposition')) ?? exportFileName(slug, format, copy.previewExportFilename);
      const blob = new Blob([bytes], { type: response.headers.get('content-type') ?? undefined });
      const url = URL.createObjectURL(blob);
      urlsRef.current.push(url);
      const file: GeneratedFile = { id: url, format, fileName: name, size: bytes.length, createdAt: new Date().toISOString(), url, validation };
      setFiles((current) => [file, ...current].slice(0, 6));
      setRun({ status: 'done', file });
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = name;
      anchor.click();
    } catch {
      setRun({ status: 'error', format, message: copy.exWsErrorNetwork });
    }
  };

  const errorText = gate.errorCount;
  const warningText = gate.warningCount;
  const plural = (count: number, one: string, many: string) => (count === 1 ? one : many.replace('{count}', String(count)));
  const live = run.status === 'busy' ? copy.exWsLiveBusy : run.status === 'done' ? copy.exWsLiveDone : run.status === 'error' ? copy.exWsLiveFail : '';
  const readyState: 'ready' | 'warn' | 'blocked' | 'unavailable' = !availability.available ? 'unavailable' : gate.blocked ? 'blocked' : gate.warningCount > 0 || gate.errorCount > 0 ? 'warn' : 'ready';
  const ctaLabel = run.status === 'busy' ? copy.exWsExporting.replace('{format}', formatLabel(format)) : original ? copy.fixedPdfExportLabel : copy.exWsExport.replace('{format}', formatLabel(format));

  return (
    <div className="ew" data-testid="export-workspace" data-format={format} data-ready={readyState} data-fixed-pdf={originalPdf ? 'true' : 'false'}>
      <div className="ew-grid">
        <section className="ew-col ew-col--formats" aria-labelledby="ew-formats-title">
          <header className="ew-head">
            <h2 id="ew-formats-title">{copy.exWsFormatsTitle}</h2>
            <p>{copy.exWsFormatsHint}</p>
          </header>
          <div
            role="radiogroup"
            aria-labelledby="ew-formats-title"
            className="ew-formats"
            data-testid="export-format-list"
            onKeyDown={(event) => {
              // Radio pattern: arrows move the selection among the available formats.
              const step = event.key === 'ArrowDown' || event.key === 'ArrowRight' ? 1 : event.key === 'ArrowUp' || event.key === 'ArrowLeft' ? -1 : 0;
              if (!step) return;
              event.preventDefault();
              const available = EXPORT_FORMATS.filter((item) => formatAvailability(item.id, capabilities).available);
              const index = available.findIndex((item) => item.id === format);
              const next = available[(index + step + available.length) % available.length];
              if (!next) return;
              setFormat(next.id);
              setRun({ status: 'idle' });
              document.querySelector<HTMLElement>(`[data-testid="export-format-${next.id}"]`)?.focus();
            }}
          >
            {EXPORT_FORMATS.map((item) => {
              const Icon = FORMAT_ICONS[item.id];
              const state = formatAvailability(item.id, capabilities);
              const selected = format === item.id;
              const isOriginal = item.id === 'pdf' && originalPdf;
              return (
                <button
                  key={item.id}
                  type="button"
                  role="radio"
                  aria-checked={selected}
                  aria-disabled={!state.available}
                  tabIndex={selected ? 0 : -1}
                  aria-describedby={`ew-format-desc-${item.id}`}
                  className="ew-format"
                  data-testid={`export-format-${item.id}`}
                  data-available={state.available ? 'true' : 'false'}
                  disabled={!state.available}
                  onClick={() => { setFormat(item.id); setRun({ status: 'idle' }); }}
                >
                  <Icon className="ew-format__icon" aria-hidden="true" />
                  <span className="ew-format__text">
                    <span className="ew-format__name">{formatLabel(item.id)} <span className="ew-badge">{kindLabel(copy, item.kind)}</span></span>
                    <span id={`ew-format-desc-${item.id}`} className="ew-format__desc">
                      {state.available ? formatDescription(copy, item.id, isOriginal) : copy.exWsUnavailableFixedPdf}
                    </span>
                  </span>
                  <span className="ew-format__radio" aria-hidden="true" data-checked={selected} />
                </button>
              );
            })}
          </div>
          {capabilities.canCreateEditableCopy ? (
            <div className="ew-editable" data-testid="export-editable-copy">
              <p>{copy.exWsUnavailableFixedPdf}</p>
              <CreateEditableCopyButton projectId={project.id} label={copy.createEditableCopyButton} className="ew-button" />
            </div>
          ) : null}
        </section>

        <section className="ew-col ew-col--config" aria-labelledby="ew-config-title" data-testid="export-config">
          <header className="ew-head">
            <h2 id="ew-config-title">{copy.exWsConfigTitle}</h2>
            <p>{copy.exWsConfigHint.replace('{format}', formatLabel(format))}</p>
          </header>

          {!availability.available ? (
            <p className="ew-note ew-note--warn" data-testid="export-unavailable" role="note">{copy.exWsUnavailableFixedPdf}</p>
          ) : null}

          {availability.available && format === 'pdf' && original ? (
            <p className="ew-note" data-testid="export-original-note">{copy.exWsPdfOriginalNote}</p>
          ) : null}

          {availability.available && definition.usesPageGeometry && !original ? (
            <div className="ew-fields" data-testid="export-page-config">
              <label className="ew-field">
                <span className="ew-field__label">{copy.exWsPageSize}</span>
                <select data-testid="export-page-size" className="ew-select" value={pageSize} onChange={(event) => setPageSize(event.target.value as typeof pageSize)} disabled={busy}>
                  {PAGE_SIZE_OPTIONS.map((option) => (<option key={option} value={option}>{pageSizeLabel(option)}</option>))}
                </select>
                <span className="ew-hint">{copy.exWsPageSizeHint}</span>
              </label>
              <dl className="ew-summary">
                <div><dt>{copy.exWsMargins}</dt><dd data-testid="export-margins">{copy.exWsMarginsValue.replace('{top}', String(geometry.marginsMm.top)).replace('{bottom}', String(geometry.marginsMm.bottom)).replace('{left}', String(geometry.marginsMm.left)).replace('{right}', String(geometry.marginsMm.right))}</dd></div>
                <div><dt>{copy.exWsTypography}</dt><dd>{copy.exWsTypographyValue.replace('{size}', String(geometry.fontSizePx)).replace('{line}', String(geometry.lineHeight))}</dd></div>
                <div><dt>{copy.exWsCoverRow}</dt><dd>{copy.exWsIncluded}</dd></div>
                <div><dt>{copy.exWsBackCoverRow}</dt><dd>{copy.exWsIncluded}</dd></div>
                {format === 'pdf' ? <div><dt>{copy.exWsNumbering}</dt><dd>{pageNumbering ? copy.exWsNumberingOn : copy.exWsNumberingOff}</dd></div> : null}
              </dl>
              <button type="button" className="ew-link" data-testid="export-edit-composition" onClick={() => props.onNavigateStep(1)}>{copy.exWsEditComposition}</button>
              {format === 'pdf' && sourcePagination ? <p className="ew-note" data-testid="export-source-note">{copy.exWsPdfSourceNote}</p> : null}
              {format === 'docx' ? (<><p className="ew-note" data-testid="export-docx-note">{copy.exWsDocxNote}</p><p className="ew-hint">{copy.exWsDocxStructure}</p></>) : null}
            </div>
          ) : null}

          {availability.available && format === 'epub' ? (
            <div className="ew-fields" data-testid="export-epub-config">
              <p className="ew-note" data-testid="export-epub-note">{copy.exWsEpubNote}</p>
              <dl className="ew-summary">
                <div><dt>{copy.exWsLanguageLabel}</dt><dd>{project.document.language || copy.exWsNotSet}</dd></div>
                <div><dt>{copy.exWsEpubNav}</dt><dd>{copy.exWsEpubNavValue}</dd></div>
              </dl>
              <p className="ew-hint">{copy.exWsEpubCoverNote}</p>
            </div>
          ) : null}
          {availability.available && format === 'html' ? <p className="ew-note" data-testid="export-html-note">{copy.exWsHtmlNote}</p> : null}
          {availability.available && format === 'markdown' ? <p className="ew-note" data-testid="export-markdown-note">{copy.exWsMarkdownNote}</p> : null}

          {availability.available && !original ? (
            <section className="ew-meta" aria-labelledby="ew-meta-title" data-testid="export-metadata">
              <h3 id="ew-meta-title" className="ew-subtitle">{copy.exWsMetadata}</h3>
              <dl className="ew-summary">
                <div><dt>{copy.exWsTitleLabel}</dt><dd data-testid="export-meta-title">{project.document.title || copy.exWsNotSet}</dd></div>
                <div><dt>{copy.exWsAuthorLabel}</dt><dd data-testid="export-meta-author">{project.document.author || copy.exWsNotSet}</dd></div>
                <div><dt>{copy.exWsLanguageLabel}</dt><dd data-testid="export-meta-language">{project.document.language || copy.exWsNotSet}</dd></div>
                <div><dt>{copy.exWsIsbnLabel}</dt><dd data-testid="export-meta-isbn">{isbn || copy.exWsNotSet}</dd></div>
              </dl>
              <button type="button" className="ew-link" data-testid="export-edit-metadata" onClick={props.onOpenDocumentData}>{copy.exWsEditMetadata}</button>
            </section>
          ) : null}

          {availability.available ? (
            <p className="ew-file"><span>{copy.exWsFileName}</span> <code data-testid="export-file-name">{fileName}</code></p>
          ) : null}
        </section>

        <section className="ew-col ew-col--check" aria-labelledby="ew-check-title" data-testid="export-final-check">
          <header className="ew-head">
            <h2 id="ew-check-title">{copy.exWsCheckTitle}</h2>
            <p>{copy.exWsCheckHint}</p>
          </header>
          <ul className="ew-checks">
            {checkRows.map((row) => (
              <li key={row.id}>
                <button type="button" className="ew-check" data-testid={`export-check-${row.id}`} data-status={row.tone} onClick={row.target} aria-label={`${row.label}: ${row.detail}. ${copy.exWsReview}`}>
                  {row.tone === 'ok' ? <CheckCircle2 className="ew-check__icon ew-check__icon--ok" aria-hidden="true" /> : row.tone === 'error' ? <XCircle className="ew-check__icon ew-check__icon--error" aria-hidden="true" /> : row.tone === 'warning' ? <AlertTriangle className="ew-check__icon ew-check__icon--warning" aria-hidden="true" /> : row.tone === 'info' ? <CircleDot className="ew-check__icon ew-check__icon--info" aria-hidden="true" /> : <MinusCircle className="ew-check__icon ew-check__icon--unchecked" aria-hidden="true" />}
                  <span className="ew-check__text">
                    <strong>{row.label}</strong>
                    <span>{row.detail}</span>
                    {row.note ? <span className="ew-hint">{row.note}</span> : null}
                  </span>
                  <ChevronRight className="ew-check__chevron" aria-hidden="true" />
                </button>
              </li>
            ))}
          </ul>
          {gate.errors.length > 0 || gate.violations > 0 ? (
            <div className="ew-blockers" data-testid="export-format-issues">
              <h3 className="ew-subtitle">{copy.exWsFormatIssues.replace('{format}', formatLabel(format))}</h3>
              <ul>
                {gate.errors.map((check) => (<li key={`${check.rule}-${check.blockId ?? ''}`}>{renderCheck(check)}</li>))}
                {gate.violations > 0 ? (<li>{copy.exWsCheckIssues.replace('{count}', String(gate.violations))} · {copy.exWsCheckComposition}</li>) : null}
              </ul>
            </div>
          ) : null}
          {props.kdpDisclosure ? <KdpDisclosurePanel disclosure={props.kdpDisclosure} copy={copy} /> : null}
        </section>
      </div>

      <section className="ew-results" aria-label={copy.exWsResultTitle}>
        {run.status === 'error' ? (
          <div role="alert" className="ew-result ew-result--error" data-testid="export-error">
            <ShieldAlert className="h-4 w-4" aria-hidden="true" />
            <div>
              <strong>{copy.exWsErrorTitle}</strong>
              <p>{run.message}</p>
              {run.failedChecks?.length ? <ul>{run.failedChecks.map((item) => (<li key={item}>{item}</li>))}</ul> : null}
            </div>
          </div>
        ) : null}
        {run.status === 'done' ? (
          <div className="ew-result ew-result--ok" data-testid="export-result" role="status">
            <CheckCircle2 className="h-4 w-4" aria-hidden="true" />
            <div>
              <strong>{copy.exWsResultTitle}</strong>
              <p><span data-testid="export-result-format">{formatLabel(run.file.format)}</span> · <span data-testid="export-result-name">{run.file.fileName}</span> · <span data-testid="export-result-size">{formatFileSize(run.file.size, locale)}</span></p>
              <p className="ew-hint" data-testid="export-result-validation">{copy.exWsResultVerified}: {run.file.validation.checks.map((check) => validationLabel(copy, check.id)).join(' · ')}</p>
            </div>
            <a className="ew-button" data-testid="export-result-download" href={run.file.url} download={run.file.fileName}><Download className="h-3.5 w-3.5" />{copy.exWsDownload}</a>
          </div>
        ) : null}
        <div className="ew-recent" data-testid="export-recent">
          <h3 className="ew-subtitle">{copy.exWsRecentTitle}</h3>
          {files.length === 0 ? <p className="ew-hint">{copy.exWsRecentEmpty}</p> : (
            <ul>
              {files.map((file) => (
                <li key={file.id} data-testid="export-recent-item">
                  <span>{file.fileName}</span><span className="ew-hint">{formatFileSize(file.size, locale)} · {new Date(file.createdAt).toLocaleTimeString(locale)}</span>
                  <a className="ew-link" href={file.url} download={file.fileName}>{copy.exWsDownload}</a>
                </li>
              ))}
            </ul>
          )}
        </div>
      </section>

      <div className="ew-bar" data-testid="export-bar" data-state={readyState}>
        <div className="ew-bar__status">
          {readyState === 'ready' ? <CheckCircle2 className="ew-bar__icon ew-bar__icon--ok" aria-hidden="true" /> : readyState === 'warn' ? <AlertTriangle className="ew-bar__icon ew-bar__icon--warning" aria-hidden="true" /> : <XCircle className="ew-bar__icon ew-bar__icon--error" aria-hidden="true" />}
          <div>
            <strong data-testid="export-status">{readyState === 'ready' || readyState === 'warn' ? copy.exWsReady : copy.exWsAttention}</strong>
            <p>
              {readyState === 'blocked' ? copy.exWsAttentionBody.replace('{format}', formatLabel(format)).replace('{count}', String(errorText))
                : readyState === 'unavailable' ? copy.exWsUnavailableFixedPdf
                  : readyState === 'warn' ? `${copy.exWsReadyBody.replace('{format}', formatLabel(format))}` : copy.exWsReadyBody.replace('{format}', formatLabel(format))}
            </p>
            {readyState !== 'unavailable' && (errorText > 0 || warningText > 0) ? (
              <p className="ew-hint" data-testid="export-counts">{plural(errorText, copy.exWsErrorsOne, copy.exWsErrorsCount)} · {plural(warningText, copy.exWsWarningsOne, copy.exWsWarningsCount)}</p>
            ) : null}
          </div>
        </div>
        <button type="button" className="ew-button ew-button--primary" data-testid="export-cta" disabled={busy || exportBlocked} aria-busy={busy} onClick={() => void generate()}>
          {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
          {ctaLabel}
        </button>
      </div>
      <div className="ew-live" role="status" aria-live="polite" data-testid="export-live">{live}</div>

      {props.children ? (
        <section className="ew-launch">
          <button type="button" className="ew-link" data-testid="export-launch-toggle" aria-expanded={launchOpen} onClick={() => setLaunchOpen((value) => !value)}>
            {launchOpen ? copy.exWsLaunchTitle : copy.exWsLaunchShow}
          </button>
          {launchOpen ? <div className="ew-launch__body">{props.children}</div> : null}
        </section>
      ) : null}
    </div>
  );
}
